### ISSUE TITLE
可以以word格式导出

### ISSUE THREAD

**Issue by TaoKing2023** [HeathKang/mubu-exporter#1]
[源码.txt](https://github.com/HeathKang/mubu-exporter/files/11069472/default.txt)

**Comment by HeathKang** [comment]
> [源码.txt](https://github.com/HeathKang/mubu-exporter/files/11069472/default.txt)

@TaoKing2023 the latest version add export word type support, thanks for your improvement.
![image](https://user-images.githubusercontent.com/16971300/229296546-7f7b5827-fc6a-4c16-a4e4-ea9aa1962b06.png)
